### PR TITLE
Add `make` as a build dependency

### PR DESCRIPTION
**Pull request by martin-g**
https://github.com/conda-forge/pigz-feedstock/pull/17 CI fails on Travis CI ([aarch64](https://app.travis-ci.com/github/conda-forge/pigz-feedstock/jobs/610080818) and ppc64le) due to:
```
+MESON_ARGS=--buildtype release --prefix=$PREFIX -Dlibdir=lib

/home/conda/feedstock_root/build_artifacts/pigz_1695116588045/work/conda_build.sh: line 22: make: command not found
```

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by martin-g** [comment]
@conda-forge-admin, please rerender

**Review by mfansler — CHANGES_REQUESTED** [review]
I'd suggest two things:

1. Include a manual migration for Arch here. That is, also reimplement [this commit](https://github.com/conda-forge/pigz-feedstock/pull/17/commits/2c8a732f506820a51ec33254520d17999a84054c) in this PR.
2. Add me (mfansler) and you (if willing) as maintainers. I actually use this tool, so I'd like to keep its recipe spiffy!

Be sure to rerender after these changes.

**Comment by martin-g** [comment]
@conda-forge-admin, please rerender

**Comment by martin-g** [comment]
@mfansler Done!

**Comment by mfansler** [comment]
@epruesse This is ready for review and merge.

**Comment by mfansler** [comment]
@conda-forge/core no response from maintainer - care to merge for us? Thanks!

**Comment by jakirkham** [comment]
Thanks all! 🙏

**Pull request merged**
